# Site settings
title:  Chi's Math Corner
description: "My personal collection of interesting math ideas"
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: Chi Tong
  email: "hienchi19@gmail.com"
  url: ""
github_username:  chitong19xx
# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
markdown: kramdown
kramdown:
  math_engine: mathjax

source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
